### ISSUE TITLE
A question about setting up firesim

### ISSUE THREAD

**Issue by ku-researcher** [CSL-KU/firesim-nvdla#13] opened 2020-01-28 16:12 UTC
I follow the instruction in README,and I try to execute the following command.

git clone https://github.com/CSL-KU/firesim-nvdla
cd firesim-nvdla
./build-setup.sh fast

When I execute ./build-setup.sh fast, I can't clone firesim-nvdla/target-design/firechip/boom.
Please teach me how to cope with this problem.

**Comment by farzad64** [comment] 2020-01-28 20:57
Could you give it a second try?

**Comment by ku-researcher** [comment] 2020-01-29 00:30
Thank you for your reply.

I try it again,but I couldn't.
When I clone firesim-nvdla/target-design/firechip/boom, I'm asked for a username and password .
Is this a private repository?
First of all,I can't access CSL-KU/firechip/boom.
URL:https://github.com/ucb-bar/riscv-boom/tree/bdcf56afbbf5f9eeccbf05fb6a077bc358c45ba6

**Comment by farzad64** [comment] 2020-01-29 01:13
The issue is the BOOM dev have moved the repo to
https://github.com/riscv-boom/riscv-boom.
I will fix this soon.

**Comment by farzad64** [comment] 2020-01-29 01:24
This must be fixed now.

**Comment by ku-researcher** [comment] 2020-01-29 09:05
Thank you for your support.
Thanks to your support,I have been able to clone firesim-nvdla/target-design/firechip/boom.

**Closed as completed** 2020-01-29 18:08 UTC
